First homework
LeonidLodygin/SPBU.2022.FunctionalProgramming.Homeworks pull request #2
Opened 2022-09-22 20:23 UTC by LeonidLodygin

The first homework consists of four functions:
1) SimplePow (Simple exponentiation of a number)
2) FastPow (Fast exponentiation of a number)
3) MinMaxFromArray (The difference between the maximum and minimum elements in the array)
4) OddNumbersArray (Get an array of odd numbers between two given)

2022-09-27 08:33 UTC, gsvgit requested changes

2022-09-27 08:33 UTC, gsvgit commented on src/Homeworks/Main.fs
> +        let mutable min = x[0]
А зачем Вам мутабельный массив? И где-то я такое странное решение уже видел.

2022-09-27 08:33 UTC, gsvgit commented on src/Homeworks/Main.fs
> +            if min > x[i] then min <- x[i] else ()
Зачем тут такой ```else``` ?

2022-09-27 08:33 UTC, gsvgit commented on src/Homeworks/Main.fs
> +                       if i % 2 <> 0 then i else ()
И тут что-то странное написано.

2022-09-27 08:33 UTC, gsvgit commented on src/Homeworks/Main.fs
> +        let var = Console.ReadLine() |> int
Раз решили с консолью так работать, пробуйте сразу Argu

2022-09-27 11:44 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +        let mutable min = x[0]
Я хотел создать переменную, которой я присваиваю значение из первой ячейки массива. Затем пробегаюсь по всему массиву и, если нахожу значение меньшее/большее, присваиваю переменной уже новое значение.

2022-09-27 11:44 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +            if min > x[i] then min <- x[i] else ()
При написании программы rider указывал на отсутствие else. На паре Вы уже подмечали этот момент, действительно, без else не ругается.

2022-09-27 11:44 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +                       if i % 2 <> 0 then i else ()
Создаю массив, проверяю, какое из полученных на вход чисел меньше, затем пробегаюсь циклом от него до второго, запихивая в массив нужные мне числа. else убрал аналогично предыдущему замечанию.

2022-09-27 11:53 UTC, gsvgit commented on src/Homeworks/Main.fs
> +                       if i % 2 <> 0 then i else ()
Ок. Мное что-то подсказывает, что можно без ```else```

2022-09-27 11:54 UTC, gsvgit commented on src/Homeworks/Main.fs
> +        let mutable min = x[0]
Проблема в том, что Вы свято верите, что в массиве есть хотя бы один элеиент. Что, если это не так?

2022-09-27 12:06 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +        let mutable min = x[0]
Понял, нужно добавить проверку на пустоту
if x = [||] then 0
else
    (*Мой код*)

2022-09-27 12:08 UTC, gsvgit commented on src/Homeworks/Main.fs
> +        let mutable min = x[0]
Ну, во-первых, лучше длину проверить. Во-вторых, точно ли ноль? Что должно вообще быть, если массив пустой?

2022-09-27 12:34 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +        let mutable min = x[0]
Проверяю длину, если ноль - завершаю функцию ошибкой.

2022-09-27 14:41 UTC, gsvgit commented on src/Homeworks/Main.fs
> +        let oddsArray =
А нельзя ли сперва понять, кто левая граница, а кто правая, а потом написать один цикл без ветвлений?

2022-09-27 14:41 UTC, gsvgit commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
А почему именно ```float```?

2022-09-27 15:02 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
В условии не был указан тип элементов, в моем случае, при получении массива со значениями типа int, они приведутся к типу float и функция выдаст результат. Если бы я указал массив с переменными int, при попытке передать функции массив с float значениями, компилятор выдал бы ошибку. То есть функция получила некоторую гибкость. Я так рассуждал.

2022-09-27 15:04 UTC, gsvgit commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
А можно ли ее сделать ещё более гибкой?

2022-09-27 15:16 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
Насколько я понял, оператор "-" поддерживает только численные типы, если я поставлю 'value в тип массива, строки он все равно не примет.

2022-09-27 15:25 UTC, gsvgit commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
Даже если так, численные не ограничиваются int и float

2022-09-27 16:29 UTC, LeonidLodygin commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
А 'value в тип элементов массива это правильный ответ?

2022-09-28 05:36 UTC, gsvgit commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: float []) =
Как вариант, да

2022-09-28 11:26 UTC, gsvgit commented on src/Homeworks/Main.fs
> +    let MinMaxFromArray (x: 'value []) =
Надо бы ещё тестов на разные типы добавить.

2022-09-29 09:39 UTC, gsvgit commented on src/Homeworks/Main.fs
> +            let mutable (ans: float) = 1.0
А зачем тут тип указывать?

2022-09-29 09:39 UTC, gsvgit commented on src/Homeworks/Main.fs
> +            printfn "Undefined"
Так undefined или 0.0 ?

2022-09-29 09:39 UTC, gsvgit commented on src/Homeworks/Main.fs
> +            printfn "Undefined"
Так undefined или 0.0 ?

2022-09-29 09:39 UTC, gsvgit commented on src/Homeworks/Main.fs
> +            for i = 1 to -a do
А можно ли обойтись одним циклом (второй на строке 28)?

2022-09-29 09:39 UTC, gsvgit commented on src/Homeworks/Main.fs
> +                    let s = FastPow n (abs a / 2)
Можно ли ```s``` объявить один раз?

2022-10-05 07:55 UTC, gsvgit approved these changes

2022-10-05 08:31 UTC, merged