Homework3
LeonidLodygin/SPBU.2022.FunctionalProgramming.Homeworks pull request #5
Opened 2022-10-22 23:13 UTC by LeonidLodygin

The third homework consists of new type ArbitraryTree and two functions:
    1. NumOfDifferentValues (Returns the number of different values in Tree)
    2. MyListOfTree (Returns List with type MyList of values from Tree)

2022-10-23 11:07 UTC, artem-burashnikov commented on tests/Homeworks.Tests/TreeTests.fs
> +                      "MyList of tree: Node(12, [|Node(1, [|Leaf(12)|]); Node(3, [|Leaf(12)|]); Node(10, [|Node(4, [|Leaf(12)|])|]); Node(15, [|Leaf(12);Leaf(1)|])|]) should be Cons(12, Cons(1, Cons(
У тебя выше в коде написаны и входные данные, и result, который ожидается, а здесь ты еще раз это  дублируешь...

2022-10-23 11:08 UTC, artem-burashnikov commented on tests/Homeworks.Tests/TreeTests.fs
> +                      "Tree: Node(\"12\", [|Node(\"1\", [|Leaf(\"12\")|]); Node(\"3\", [|Leaf(\"12\")|]); Node(\"10\", [|Node(\"4\", [|Leaf(\"12\")|])|]); Node(\"15\", [|Leaf(\"12\");Leaf(\"1\")|])|]
И тут тоже. Выше как бы это и написано.

2022-10-23 11:11 UTC, artem-burashnikov commented on tests/Homeworks.Tests/TreeTests.fs
> +                  Expect.equal Result 1 "Tree with the same values has only 1 value"
```suggestion
                  Expect.equal Result 1 "The number of unique elements in a tree whose elements are the same is 1."
```

2022-10-23 11:11 UTC, artem-burashnikov commented on tests/Homeworks.Tests/TreeTests.fs
> +                  <| "Length of MyList should be greater or equal to the number of different values"
```suggestion
                  <| "Length of MyList should be greater than or equal to the number of different values"
```

2022-10-24 06:02 UTC, gsvgit commented
Разрулите, пожалуйста, конфликты с основной веткой.

2022-10-24 06:09 UTC, gsvgit requested changes

2022-10-24 06:09 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +            for i in array do
Бывает ```Array.iter```

2022-10-24 06:09 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +    Counter(tree)
Старайтесь избегать лишних скобок.

2022-10-24 06:09 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +let rec MyListOfTree (tree: ArbitraryTree<'value>) =
Посомтрите на эту функцию и на  ```NumOfDifferentValues``` как на функции, которые обходят дерево и что-то делают со значениями в узлах. И попробуйте их унифицировать.

2022-10-24 08:53 UTC, LeonidLodygin commented
Исправления по коду сделал. По поводу merge conflct. Ничего умнее, чем залить новые изменения coverage файлов в main ветку я не придумал, поэтому она перестала собираться.(По понятным причинам). Если можно держать ее в таком состоянии до слияния с этой веткой, то все исправится. Если нужно сделать так, чтобы merge conflict отсутствовал, но при этом main бы билдился, тогда я не совсем понимаю, как это возможно сделать.

2022-10-24 10:55 UTC, gsvgit commented
А теперь представьте, что в мастер изменения могут попадать только через реквесты. Так что в идеале Вам надо что-то менять в ветке с домашкой. Давайте попробуем ещё разок. Стабилизируем мастер (чтобы собирался). А дальше маржим мастер в ветку и решаем конфликты.

2022-10-24 12:51 UTC, gsvgit requested changes

2022-10-24 12:51 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +    match tree with
Уже лучше, но нет. Посомтрите на map у списка: штука умеет ходить по списку и приментять произвольную функцию. Тут примертно такая же история. Надо отделить обход дерева от произвольных действий с каждым узлом.

2022-10-24 12:51 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +    let hashSet = new HashSet<'value>()
А вот тут просто передать нужное действие.

2022-10-24 12:51 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +    let hashSet = new HashSet<'value>()
И тут. Но, вероятно, какое-то другое.

2022-10-24 12:51 UTC, gsvgit commented on docs/coverage/Homeworks_FirstHomework.html
>  </script>
Тут явно что-то странное поменялось.

2022-10-29 07:01 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +    let recur = ArrayWalker func
Откуда у всех этот странный шаблон? И ладно бы эта функция потом несколько раз использовалась. Так ведь вообще не понятно, зачем её выделили.

2022-10-29 07:01 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +    match arr with
Это точно не Array.fold ?

2022-10-29 07:01 UTC, gsvgit commented on src/Homeworks/Tree.fs
> +let rec TreeWalker hell answer tree =
Отличные названия у переменных.

2022-10-29 07:23 UTC, LeonidLodygin commented on src/Homeworks/Tree.fs
> +    let recur = ArrayWalker func
Задачу на отделение обхода дерева от взаимодействия со значениями мне помогал решать один из одногруппников, ничего не получалось(отсюда и название переменной, запамятовал поменять, извиняюсь), поэтому в какой то момент решение пришло к такому же шаблону.

2022-11-03 08:43 UTC, gsvgit approved these changes

2022-11-03 12:05 UTC, merged