Hw4 version 1.0
LeonidLodygin/SPBU.2022.FunctionalProgramming.Homeworks pull request #6
Opened 2022-11-27 15:22 UTC by LeonidLodygin

The fourth homework consists of new types SparseVector and SparseMatrix with two main functions:
1. FAddVector (Returns the sum of two SparseVectors)
2. MultiplyVecMat (Returns the multiplication of SparseVector by SparseMatrix)
3. Tests also

2022-11-28 07:51 UTC, gsvgit requested changes

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/MultiMatrix.fs
> +    | _ -> failwith $"No value"
А почему здесь надо падать? None --- хорошее значение как результат поэлементной оперции.

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/MultiMatrix.fs
> +let FAddVector
Группировка странная. Казалось бы, операции над векторами можно поселить рядом с векторами.

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +        val Head: int * int
А почему голова --- это два инта? То ли название поля странное, то ли там не два инта.

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +    | Node of Fst: QuadTree<'value> * Snd: QuadTree<'value> * Thd: QuadTree<'value> * Fth: QuadTree<'value>
А в каком порядке Вы квадранты нумеруете?

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +            Node(helper (fst), helper (snd), helper (thd), helper (fth))
А зачем тут столько скобочек?

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +    member this.getItem x y =
Можно красивее: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/members/indexed-properties

2022-11-28 07:51 UTC, gsvgit commented on src/Homeworks/SparseVector.fs
> +let ClosestDegreeOf2 (length: int) =
Чот похоже на дублирование кода.

2022-11-28 07:51 UTC, gsvgit commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +        | Some x, Some y -> Some(x + y)
То есть None Вы никогда не можете получить из двух "значащих" элементов? А если они "взаимнообратные"?

2022-11-28 07:51 UTC, gsvgit commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +        | Some x, Some y -> Some(x * y)
Ну и тут аналогичный вопрос. Хотя тут не про "обратность", конечно.

2022-11-28 07:51 UTC, gsvgit commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +                      |> Array.map (fun x -> if x > 2 then Option.None else Some(x))
Дублирование кода.

2022-11-29 05:45 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +        val Coordinates: int * int
Coordinates кого?

2022-11-29 05:45 UTC, gsvgit commented on src/Homeworks/SparseVector.fs
> +    | _ -> Leaf(x |> GetValue)
Что-то тут странное написано. Мы же уже сматчили `x`. Зачем его ещё раз передавать и матчить с тем же самым?

2022-11-29 05:45 UTC, gsvgit commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +                  let Result = GetValue(Some 5)
Эм... Это чтобы никто не догадался, что это просто 5 ?

2022-11-29 05:45 UTC, gsvgit commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +                      skiptest |> ignore
А здесь sciptest точно нормально работает, или как у нас на паре тогда?)

2022-11-29 05:45 UTC, gsvgit commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +            "Some multiply property tests"
И всё же проверьте, что у Вас все деревья всегда редуцированы.

2022-11-29 05:56 UTC, LeonidLodygin commented on src/Homeworks/SparseVector.fs
> +    | _ -> Leaf(x |> GetValue)
Есть функция GetValue. Она просто возвращает value, если оно есть. А есть NoneOrValue. Она возвращает лист со значением, если оно есть или BinaryTree.None, если там Option.None. Почему это странно? Две разные функции.

2022-11-29 06:06 UTC, gsvgit commented on src/Homeworks/SparseVector.fs
> +    | _ -> Leaf(x |> GetValue)
Да меня, если честно, сама функция GetValue пугает. Потому что мы знаем, что None - это не упасть, а вернуть некий "ноль". 

А конкретно здесь ещё и какое-то странное переусложнение. Примерно как если бы вместо того, чтобы просто прибавить константу, Вы бы для каждой константы писали функцию, которая ее прибавляет и потом ее вызывали. Логично же.

2022-11-29 12:02 UTC, LeonidLodygin commented on tests/Homeworks.Tests/MultiplyVecMat.fs
> +                      skiptest |> ignore
Проверил еще раз с помощью breakpoints, все работает как нужно, скипает только определенные тесты, а не весь тест целиком.

2022-11-29 14:17 UTC, gsvgit approved these changes

2022-11-29 14:30 UTC, merged