Homework5
LeonidLodygin/SPBU.2022.FunctionalProgramming.Homeworks pull request #7
Opened 2022-12-12 23:17 UTC by LeonidLodygin

The fifth homework consists of two auxiliary functions: VecFromList and MatrixFromList. And one main function - Bfs.
1. VecFromList receives a list of vertices with weights as input and returns vector.
2. MatrixFromList recieves a list of coordinates with values as input and returns matrix.
3. Bfs recieves list of vertieces and graph and returns the reachability vector of vertices on the graph from the input vertieces.
4. Tests also

2022-12-13 06:04 UTC, gsvgit requested changes

2022-12-13 06:04 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +    | Some true, _ -> Some true
Забавно, что у вас булев тип использутся, хотя на самом деле Вам нужен тип содним значением, а не с двумя.

2022-12-13 06:04 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +let Bfs (graph: List<int * int * 'a option>) (apexes: List<int * bool>) size =
А кто такой второй аргумент? И третий. BFS должен принимать просто граф и множество стартовых вершин.

2022-12-13 06:04 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +    let matrix = MatrixFromList graph size
А вот чем отличается конструирование матрицы из плотной и матрицы из координатного формата?

2022-12-13 06:04 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +    let front = VecFromList apexes size
Ну и тот же вопрос про вектор.

2022-12-13 06:04 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +                FAddVector Mask (MultiplyVecMat front matrix FrontAdd FrontMult) visited
И всё же уходите от этого дурного стиля когда каие-то имена с маленькой, какие-то с большой.

2022-12-13 06:04 UTC, gsvgit commented on tests/Homeworks.Tests/BfsTests.fs
> +                      skiptest |> ignore
Что?

2022-12-13 06:04 UTC, gsvgit commented on tests/Homeworks.Tests/BfsTests.fs
> +                      let naiveBFS (start: int list) (arr: 'a option [,]) =
И вот кому я про угловыу скобки рассказывал?

2022-12-14 06:45 UTC, gsvgit requested changes

2022-12-14 06:45 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +            Array.init graph.Columns (fun x ->
И Вы тоже про init слишком буквально поняли. Это был просто пример функции, которая может создать коллекцию с нужными значениями в нужных позициях.

2022-12-14 06:45 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +                    Some true
Ну и вопрос про bool пока остаётся.

2022-12-14 06:45 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +          Lines = size
А.... А почему в одном случае честно и строчки и столбцы, а тут просто "размер"?

2022-12-14 06:45 UTC, gsvgit commented on tests/Homeworks.Tests/BfsTests.fs
> +                      let QueueFormatter queue apex iter =
В стандартных коллекциях есть нормальная очередь.

2022-12-14 06:45 UTC, gsvgit commented on tests/Homeworks.Tests/BfsTests.fs
> +                  let resultList =
А можно было бы просто по листу получить максимальные корректные координаты. А если бы был ещё такой тип, в котором нету отрицательных значений, то вообще сказка была бы.

2022-12-14 17:16 UTC, LeonidLodygin commented on src/Homeworks/SparseMatrix.fs
> +          Lines = size
Потому что создается квадратная матрица.

2022-12-14 19:42 UTC, gsvgit commented on src/Homeworks/SparseMatrix.fs
> +          Lines = size
А что, я не могу списком координат задать не квадратную матрицу?

2022-12-16 06:04 UTC, gsvgit reviewed
Уже почти идеально.

2022-12-16 06:04 UTC, gsvgit commented on src/Homeworks/BreadthFirstSearch.fs
> +        FAddVector(SuperSum 0u) front (SparseVector(Array.create (int front.Length) Option.None))
Что-то странное. То есть Вы таки сперва создаёте плотный массив из одних None. То есть в при переход в вектор он становится пустым.... Зачем так?

2022-12-16 08:29 UTC, gsvgit approved these changes

2022-12-16 12:55 UTC, merged